import { apiClient } from '@/src/lib/api';

export type PaymentMethod = 'cash' | 'card' | 'credits';

export interface CreateReservationRequest {
  restaurant_id?: number;
  location_id?: number;
  basket_id?: number;
  quantity: number;
  payment_method?: PaymentMethod;
  /**
   * Wallet credits (TND) applied as a partial discount. The remainder
   * (total − credit_amount) is funded by `payment_method` (cash/card). The
   * credit slice is returned to the partner in full at settlement.
   */
  credit_amount?: number;
  /**
   * Defer the server-side notification fan-out (buyer + every business
   * member) by this many milliseconds AFTER the reservation row is
   * committed. The reservation itself is still created immediately; only
   * the bell-row INSERTs and the OS push dispatches wait. Used by the
   * reserve flow to keep notifications from popping over the in-app
   * confirmation animation. Server clamps to [0, 15000] ms.
   */
  notification_delay_ms?: number;
  /**
   * Per-attempt UUID generated by reserve.tsx when the user hits Confirmer.
   * Sent as the `Idempotency-Key` header AND in the body as a fallback. If
   * the same key arrives twice (network retry, ghost-order recovery), the
   * backend returns the original reservation instead of creating a
   * duplicate. The key persists across retries of the SAME attempt and is
   * reset whenever the cart state changes (qty/credit/payment/basket).
   */
  idempotency_key?: string;
}

export interface ReservationFromAPI {
  id: string;
  restaurant_id?: number;
  basketId?: string;
  /** Name of the basket type (e.g. "Panier Surprise Boulangerie") */
  basket_name?: string;
  basket_type_name?: string;
  basket?: {
    id: string;
    /** Basket type name — the primary label customers see */
    name?: string;
    /** Alternative field names returned by some API versions */
    basket_type_name?: string;
    type_name?: string;
    basket_name?: string;
    merchantName?: string;
    merchant_name?: string;
    merchantLogo?: string;
    image_url?: string;
    originalPrice?: number;
    original_price?: string;
    discountedPrice?: number;
    price_tier?: string;
    pickupWindow?: { start: string; end: string };
    pickup_start_time?: string;
    pickup_end_time?: string;
    address?: string;
    latitude?: number;
    longitude?: number;
    quantityLeft?: number;
    quantityTotal?: number;
    imageUrl?: string;
    [key: string]: unknown;
  };
  restaurant?: {
    id: number;
    name?: string;
    address?: string;
    image_url?: string;
    price_tier?: string;
    original_price?: string;
    pickup_start_time?: string;
    pickup_end_time?: string;
    latitude?: number;
    longitude?: number;
    [key: string]: unknown;
  };
  quantity?: number;
  total?: number;
  total_price?: string;
  pickupWindow?: {
    start: string;
    end: string;
  };
  pickupCode?: string;
  pickup_code?: string;
  qrCode?: string;
  status?: string;
  createdAt?: string;
  created_at?: string;
  [key: string]: unknown;
}

export async function createReservation(data: CreateReservationRequest): Promise<ReservationFromAPI> {
  console.log('[Reservations] Creating reservation for location:', data.location_id ?? data.restaurant_id, 'qty:', data.quantity);
  // Per-request 60s timeout override. The default apiClient timeout (15s) was
  // tripping on slow backends — the reservation endpoint does its business-
  // member notification fanout + badge queries inline (see backend
  // routes/reservations.js POST '/'), which can push the response past 15s
  // when an org has several members or the push-notif provider is sluggish.
  // The transaction commits server-side, so a client-side timeout produced
  // a misleading "no internet" error while the order had actually gone
  // through. 60s is generous enough to cover real-world fanout without
  // hiding a genuinely-stuck request forever. The companion recovery path
  // in reserve.tsx (onError → fetchMyReservations → match check) catches
  // the rare case where the timeout still fires.
  // Header takes precedence; body field is a redundant fallback so even an
  // intermediate layer that strips custom headers (some corporate proxies do)
  // still gets the dedup key through to the backend.
  const idempotencyKey = data.idempotency_key && data.idempotency_key.length > 0 ? data.idempotency_key : undefined;
  const res = await apiClient.post<ReservationFromAPI | { reservation: ReservationFromAPI } | { data: ReservationFromAPI }>('/api/reservations', {
    location_id: data.location_id,
    restaurant_id: data.restaurant_id,
    basket_id: data.basket_id,
    quantity: data.quantity,
    payment_method: data.payment_method,
    credit_amount: data.credit_amount,
    client_request_id: idempotencyKey,
  }, {
    timeout: 60_000,
    headers: idempotencyKey ? { 'Idempotency-Key': idempotencyKey } : undefined,
  });
  const resData = res.data;
  let reservation: ReservationFromAPI;
  if (resData && typeof resData === 'object' && 'reservation' in resData) {
    reservation = (resData as any).reservation;
  } else if (resData && typeof resData === 'object' && 'data' in resData) {
    reservation = (resData as any).data;
  } else {
    reservation = resData as ReservationFromAPI;
  }
  console.log('[Reservations] Created reservation:', reservation.id);
  return reservation;
}

export async function fetchMyReservations(): Promise<ReservationFromAPI[]> {
  console.log('[Reservations] Fetching my reservations');
  const res = await apiClient.get<ReservationFromAPI[] | { reservations: ReservationFromAPI[] } | { data: ReservationFromAPI[] }>('/api/reservations/my/reservations');
  const data = res.data;
  let reservations: ReservationFromAPI[];
  if (Array.isArray(data)) {
    reservations = data;
  } else if (data && typeof data === 'object' && 'reservations' in data && Array.isArray((data as any).reservations)) {
    reservations = (data as any).reservations;
  } else if (data && typeof data === 'object' && 'data' in data && Array.isArray((data as any).data)) {
    reservations = (data as any).data;
  } else {
    console.log('[Reservations] Unexpected response shape:', JSON.stringify(data).substring(0, 200));
    reservations = [];
  }
  console.log('[Reservations] Fetched', reservations.length, 'reservations');
  return reservations;
}

/**
 * Lightweight reservation summary used by the chat screen to render the
 * OrderSummaryCard at the top before any conversation row exists. The
 * backend GET /api/reservations/:id endpoint returns these fields in
 * addition to the standard reservation columns; the chat screen falls
 * back to them when conversation.res_* aren't populated yet.
 */
export interface ReservationSummary {
  id: number;
  quantity?: number;
  total?: number | string | null;
  basket_name?: string | null;
  basket_image_url?: string | null;
  restaurant_name?: string | null;
  org_logo_url?: string | null;
  /** Buyer's display name — populated for the business-side chat header
   *  before any conversation row exists for the reservation. */
  buyer_name?: string | null;
}

export async function fetchReservationById(reservationId: string | number): Promise<ReservationSummary | null> {
  try {
    const res = await apiClient.get<any>(`/api/reservations/${reservationId}`);
    return (res.data ?? null) as ReservationSummary | null;
  } catch {
    return null;
  }
}

export async function fetchReservationQRCode(reservationId: string): Promise<string> {
  console.log('[Reservations] Fetching QR code for:', reservationId);
  const res = await apiClient.get<{ qrCode: string } | { data: string } | string>(`/api/reservations/${reservationId}/qrcode`);
  const data = res.data;
  if (typeof data === 'string') return data;
  if (data && typeof data === 'object' && 'qrCode' in data) return (data as any).qrCode;
  if (data && typeof data === 'object' && 'data' in data) return (data as any).data;
  return '';
}

export async function cancelReservation(reservationId: string, reason?: string): Promise<void> {
  console.log('[Reservations] Cancelling reservation:', reservationId, reason ? `reason: ${reason}` : '');
  await apiClient.delete(`/api/reservations/${reservationId}`, reason ? { data: { reason } } : undefined);
  console.log('[Reservations] Cancelled reservation:', reservationId);
}

export async function dismissReviewPrompt(reservationId: string): Promise<void> {
  console.log('[Reservations] Dismissing review prompt for:', reservationId);
  await apiClient.put(`/api/reservations/${reservationId}/dismiss-review`);
  console.log('[Reservations] Dismissed review prompt:', reservationId);
}

export async function hideReservation(reservationId: string): Promise<void> {
  console.log('[Reservations] Hiding reservation:', reservationId);
  await apiClient.put(`/api/reservations/${reservationId}/hide`);
  console.log('[Reservations] Hidden reservation:', reservationId);
}
